//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Decor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string Artikul { get; set; }
        public Nullable<int> Coust { get; set; }
        public Nullable<int> MaxDiscount { get; set; }
        public Nullable<int> IDProizvoditel { get; set; }
        public Nullable<int> IDPostavchik { get; set; }
        public Nullable<int> IDCategory { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> Count { get; set; }
        public string Description { get; set; }
        public string PhotoPath { get; set; }
        public Nullable<int> IDUnit { get; set; }
        public string Name { get; set; }
    
        public virtual Postavchik Postavchik { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual Proizvoditel Proizvoditel { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
